
import React, { useState } from 'react';
import { WORKFLOWS, Workflow, WorkflowStep } from '../data/workflows';

interface FilingNavigatorProps {
    onNavigate: (view: string, resourceId?: string) => void;
}

const FilingNavigator: React.FC<FilingNavigatorProps> = ({ onNavigate }) => {
  const [selectedWorkflow, setSelectedWorkflow] = useState<Workflow | null>(null);
  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [completedSteps, setCompletedSteps] = useState<Record<string, boolean>>({});

  const handleWorkflowSelect = (wf: Workflow) => {
    setSelectedWorkflow(wf);
    setActiveStepIndex(0);
    setCompletedSteps({});
  };

  const handleStepComplete = () => {
    if (!selectedWorkflow) return;
    const currentStep = selectedWorkflow.steps[activeStepIndex];
    setCompletedSteps(prev => ({ ...prev, [currentStep.id]: true }));
    
    if (activeStepIndex < selectedWorkflow.steps.length - 1) {
        setActiveStepIndex(prev => prev + 1);
    }
  };

  const handleStepClick = (index: number) => {
      if (index <= activeStepIndex || completedSteps[selectedWorkflow!.steps[index-1]?.id]) {
          setActiveStepIndex(index);
      }
  };

  const handleExportGuide = () => {
    if (!selectedWorkflow) return;
    const lines = [
        `VEROBRIX FILING GUIDE: ${selectedWorkflow.title.toUpperCase()}`,
        `==================================================`,
        `${selectedWorkflow.description}`,
        `\nSTEPS:`,
        ...selectedWorkflow.steps.map((step, i) => {
            return `\n${i+1}. ${step.title.toUpperCase()}\n   ${step.description}\n   INSTRUCTIONS:\n   ${step.instructions.map(inst => `- ${inst}`).join('\n   ')}`
        }),
        `\n==================================================`,
        `Generated by Verobrix Sovereign Cockpit`
    ];
    
    const element = document.createElement("a");
    const file = new Blob([lines.join('\n')], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `${selectedWorkflow.id}_guide.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex h-full bg-slate-950">
      {/* Workflow Selector Pane */}
      <div className="w-80 bg-slate-900 border-r border-slate-800 flex flex-col shrink-0">
        <div className="p-6 border-b border-slate-800">
          <h2 className="font-serif font-bold text-sovereign-200 text-lg">Filing Navigator</h2>
          <p className="text-xs text-slate-500 font-mono mt-1">Guided procedural workflows.</p>
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-2">
            {WORKFLOWS.map(wf => (
                <button
                    key={wf.id}
                    onClick={() => handleWorkflowSelect(wf)}
                    className={`w-full text-left p-3 rounded border transition-all ${
                        selectedWorkflow?.id === wf.id 
                            ? 'bg-sovereign-900/30 border-sovereign-500 text-sovereign-100' 
                            : 'bg-slate-950 border-slate-800 text-slate-400 hover:bg-slate-800 hover:text-slate-200'
                    }`}
                >
                    <h3 className="font-bold text-sm mb-1">{wf.title}</h3>
                    <p className="text-[10px] opacity-70 truncate">{wf.description}</p>
                </button>
            ))}
        </div>
      </div>

      {/* Workflow Engine Pane */}
      <div className="flex-1 p-8 overflow-y-auto flex flex-col">
        {selectedWorkflow ? (
            <div className="max-w-4xl mx-auto w-full">
                <header className="mb-8 flex justify-between items-start">
                    <div>
                        <h1 className="text-3xl font-serif font-bold text-sovereign-200 mb-2">{selectedWorkflow.title}</h1>
                        <p className="text-slate-400 font-mono text-sm max-w-2xl">{selectedWorkflow.description}</p>
                    </div>
                    <button 
                        onClick={handleExportGuide}
                        className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded border border-slate-600 text-xs font-mono flex items-center"
                    >
                        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                        EXPORT GUIDE
                    </button>
                </header>

                {/* Progress Bar */}
                <div className="flex items-center space-x-2 mb-8 overflow-x-auto pb-4 scrollbar-hide">
                    {selectedWorkflow.steps.map((step, idx) => (
                        <div key={step.id} className="flex items-center shrink-0">
                             <div 
                                onClick={() => handleStepClick(idx)}
                                className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-xs cursor-pointer border-2 transition-colors ${
                                    idx === activeStepIndex 
                                        ? 'bg-sovereign-600 border-sovereign-600 text-white shadow-[0_0_10px_rgba(212,162,86,0.5)]'
                                        : completedSteps[step.id] 
                                            ? 'bg-emerald-900 border-emerald-600 text-emerald-400' 
                                            : 'bg-slate-900 border-slate-700 text-slate-600'
                                }`}
                             >
                                {completedSteps[step.id] ? '✓' : idx + 1}
                             </div>
                             {idx < selectedWorkflow.steps.length - 1 && (
                                 <div className={`w-12 h-0.5 mx-2 ${
                                     completedSteps[step.id] ? 'bg-emerald-800' : 'bg-slate-800'
                                 }`}></div>
                             )}
                        </div>
                    ))}
                </div>

                {/* Active Step Card */}
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                        <svg className="w-32 h-32 text-sovereign-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                        </svg>
                    </div>

                    <div className="relative z-10">
                        <span className="text-xs font-mono text-sovereign-500 uppercase tracking-widest mb-2 block">Step {activeStepIndex + 1} of {selectedWorkflow.steps.length}</span>
                        <h2 className="text-2xl font-serif font-bold text-white mb-4">{selectedWorkflow.steps[activeStepIndex].title}</h2>
                        <p className="text-slate-400 mb-6">{selectedWorkflow.steps[activeStepIndex].description}</p>

                        <div className="bg-slate-950/50 rounded-lg p-6 border border-slate-800 mb-6">
                            <h3 className="text-xs font-bold text-emerald-500 uppercase mb-4 flex items-center">
                                <span className="w-2 h-2 bg-emerald-500 rounded-full mr-2"></span>
                                Instructions
                            </h3>
                            <ul className="space-y-3">
                                {selectedWorkflow.steps[activeStepIndex].instructions.map((inst, i) => (
                                    <li key={i} className="flex items-start text-sm text-slate-300 font-mono">
                                        <span className="mr-3 text-slate-600">{i+1}.</span>
                                        {inst}
                                    </li>
                                ))}
                            </ul>
                        </div>

                        {/* Resources */}
                        <div className="flex flex-wrap gap-4 mb-8">
                             {selectedWorkflow.steps[activeStepIndex].recommendedScriptId && (
                                 <button 
                                    onClick={() => onNavigate('scripts', selectedWorkflow.steps[activeStepIndex].recommendedScriptId)}
                                    className="flex items-center space-x-2 bg-blue-900/20 hover:bg-blue-900/40 px-4 py-3 rounded border border-blue-900/50 transition-colors group text-left"
                                 >
                                     <div className="p-2 bg-blue-900/30 rounded group-hover:bg-blue-800/50">
                                        <svg className="w-5 h-5 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" /></svg>
                                     </div>
                                     <div>
                                        <span className="text-[10px] text-blue-300 font-bold uppercase block mb-0.5">Recommended Script</span>
                                        <span className="text-xs text-white font-mono block">Launch Verbal Protocol &rarr;</span>
                                     </div>
                                 </button>
                             )}
                             {selectedWorkflow.steps[activeStepIndex].recommendedTemplateId && (
                                 <button 
                                    onClick={() => onNavigate('drafter', selectedWorkflow.steps[activeStepIndex].recommendedTemplateId)}
                                    className="flex items-center space-x-2 bg-purple-900/20 hover:bg-purple-900/40 px-4 py-3 rounded border border-purple-900/50 transition-colors group text-left"
                                 >
                                     <div className="p-2 bg-purple-900/30 rounded group-hover:bg-purple-800/50">
                                        <svg className="w-5 h-5 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                                     </div>
                                     <div>
                                        <span className="text-[10px] text-purple-300 font-bold uppercase block mb-0.5">Recommended Template</span>
                                        <span className="text-xs text-white font-mono block">Open in Drafter &rarr;</span>
                                     </div>
                                 </button>
                             )}
                        </div>

                        <div className="flex justify-between items-center">
                            <button 
                                onClick={() => handleStepClick(activeStepIndex - 1)}
                                disabled={activeStepIndex === 0}
                                className="px-4 py-2 text-slate-500 hover:text-slate-300 disabled:opacity-30 disabled:cursor-not-allowed text-xs font-mono"
                            >
                                ← PREVIOUS STEP
                            </button>
                            <button 
                                onClick={handleStepComplete}
                                className="px-6 py-3 bg-sovereign-700 hover:bg-sovereign-600 text-white font-bold font-serif rounded shadow-lg transition-all flex items-center text-sm"
                            >
                                {activeStepIndex === selectedWorkflow.steps.length - 1 ? 'FINISH PROTOCOL' : 'COMPLETE & PROCEED →'}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        ) : (
            <div className="h-full flex flex-col items-center justify-center text-slate-600 opacity-50">
                <svg className="w-16 h-16 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                </svg>
                <p className="font-serif text-lg">Select a workflow to begin guidance.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default FilingNavigator;